"""phase 2 core schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 16:24:23.961834
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.db.types
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_counters',
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prefix', name=op.f('pk_code_counters'))
    )
    op.create_table('intersections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('approach_radius_m', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='intersectionstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('controller_type', sa.Enum('FIXED', 'ADAPTIVE', name='controllertype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('actuator', sa.Enum('SUMO', 'HARDWARE', 'DISPLAY_ONLY', name='actuatortype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('sumo_tls_id', sa.String(length=64), nullable=True),
    sa.Column('assumed_penetration_rate', sa.Float(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('approach_radius_m > radius_m', name=op.f('ck_intersections_approach_outside_core')),
    sa.CheckConstraint('assumed_penetration_rate > 0 AND assumed_penetration_rate <= 1', name=op.f('ck_intersections_penetration_range')),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_intersections_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_intersections_longitude_range')),
    sa.CheckConstraint('radius_m > 0', name=op.f('ck_intersections_radius_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intersections')),
    sa.UniqueConstraint('code', name=op.f('uq_intersections_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('END_USER', 'MANAGER', 'ADMIN', name='userrole', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('controller_clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('RASPBERRY_PI', 'SUMO_BRIDGE', 'CAMERA', 'OTHER', name='controllerclientkind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_controller_clients_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_controller_clients')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_controller_clients_key_hash')),
    sa.UniqueConstraint('name', name=op.f('uq_controller_clients_name'))
    )
    op.create_table('intersection_approaches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intersection_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('travel_bearing_deg', sa.Float(), nullable=False),
    sa.Column('bearing_tolerance_deg', sa.Float(), nullable=False),
    sa.Column('lanes', sa.Integer(), nullable=False),
    sa.Column('zone_length_m', sa.Float(), nullable=False),
    sa.Column('free_flow_speed_mps', sa.Float(), nullable=False),
    sa.Column('upstream_intersection_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('bearing_tolerance_deg > 0 AND bearing_tolerance_deg <= 90', name=op.f('ck_intersection_approaches_tolerance_range')),
    sa.CheckConstraint('free_flow_speed_mps > 0', name=op.f('ck_intersection_approaches_free_flow_positive')),
    sa.CheckConstraint('lanes >= 1', name=op.f('ck_intersection_approaches_lanes_positive')),
    sa.CheckConstraint('travel_bearing_deg >= 0 AND travel_bearing_deg < 360', name=op.f('ck_intersection_approaches_bearing_range')),
    sa.CheckConstraint('zone_length_m > 0', name=op.f('ck_intersection_approaches_zone_positive')),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], name=op.f('fk_intersection_approaches_intersection_id_intersections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_intersection_id'], ['intersections.id'], name=op.f('fk_intersection_approaches_upstream_intersection_id_intersections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intersection_approaches')),
    sa.UniqueConstraint('intersection_id', 'name', name=op.f('uq_intersection_approaches_intersection_id_name'))
    )
    op.create_index(op.f('ix_intersection_approaches_intersection_id'), 'intersection_approaches', ['intersection_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('installation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('NORMAL', 'AMBULANCE', 'FIRE_TRUCK', 'POLICE', name='vehicletype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'RETIRED', name='vehiclestatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_vehicles_owner_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('code', name=op.f('uq_vehicles_code'))
    )
    op.create_index(op.f('ix_vehicles_owner_user_id'), 'vehicles', ['owner_user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_client_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_client_id'], ['controller_clients.id'], name=op.f('fk_audit_logs_actor_client_id_controller_clients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('controller_client_scopes',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('intersection_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['controller_clients.id'], name=op.f('fk_controller_client_scopes_client_id_controller_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], name=op.f('fk_controller_client_scopes_intersection_id_intersections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'intersection_id', name=op.f('pk_controller_client_scopes'))
    )
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('installation_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.Enum('ANDROID', 'IOS', name='deviceplatform', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='devicestatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('bound_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('unbound_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_devices_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('vehicle_id', 'installation_id', name=op.f('uq_devices_vehicle_id_installation_id'))
    )
    op.create_index(op.f('ix_devices_installation_id'), 'devices', ['installation_id'], unique=False)
    op.create_index('ix_devices_one_active_per_vehicle', 'devices', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.create_index(op.f('ix_devices_vehicle_id'), 'devices', ['vehicle_id'], unique=False)
    op.create_table('emergency_authorizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REVOKED', name='authorizationstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('valid_until', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_emergency_authorizations_requested_by_users')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_emergency_authorizations_reviewed_by_users')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_emergency_authorizations_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_authorizations'))
    )
    op.create_index(op.f('ix_emergency_authorizations_vehicle_id'), 'emergency_authorizations', ['vehicle_id'], unique=False)
    op.create_table('intersection_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_intersection_id', sa.Uuid(), nullable=False),
    sa.Column('to_intersection_id', sa.Uuid(), nullable=False),
    sa.Column('to_approach_id', sa.Uuid(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('free_flow_speed_mps', sa.Float(), nullable=False),
    sa.CheckConstraint('distance_m > 0', name=op.f('ck_intersection_links_distance_positive')),
    sa.CheckConstraint('free_flow_speed_mps > 0', name=op.f('ck_intersection_links_free_flow_positive')),
    sa.CheckConstraint('from_intersection_id <> to_intersection_id', name=op.f('ck_intersection_links_no_self_link')),
    sa.ForeignKeyConstraint(['from_intersection_id'], ['intersections.id'], name=op.f('fk_intersection_links_from_intersection_id_intersections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_approach_id'], ['intersection_approaches.id'], name=op.f('fk_intersection_links_to_approach_id_intersection_approaches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_intersection_id'], ['intersections.id'], name=op.f('fk_intersection_links_to_intersection_id_intersections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intersection_links')),
    sa.UniqueConstraint('from_intersection_id', 'to_intersection_id', name=op.f('uq_intersection_links_from_intersection_id_to_intersection_id'))
    )
    op.create_index(op.f('ix_intersection_links_from_intersection_id'), 'intersection_links', ['from_intersection_id'], unique=False)
    op.create_index(op.f('ix_intersection_links_to_intersection_id'), 'intersection_links', ['to_intersection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intersection_links_to_intersection_id'), table_name='intersection_links')
    op.drop_index(op.f('ix_intersection_links_from_intersection_id'), table_name='intersection_links')
    op.drop_table('intersection_links')
    op.drop_index(op.f('ix_emergency_authorizations_vehicle_id'), table_name='emergency_authorizations')
    op.drop_table('emergency_authorizations')
    op.drop_index(op.f('ix_devices_vehicle_id'), table_name='devices')
    op.drop_index('ix_devices_one_active_per_vehicle', table_name='devices', postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_devices_installation_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('controller_client_scopes')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vehicles_owner_user_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_intersection_approaches_intersection_id'), table_name='intersection_approaches')
    op.drop_table('intersection_approaches')
    op.drop_table('controller_clients')
    op.drop_table('users')
    op.drop_table('intersections')
    op.drop_table('code_counters')
    # ### end Alembic commands ###
