"""phase 3-8 telemetry emergency traffic signals

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 16:24:26.183791
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.db.types
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intersection_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_until', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('cycle_s', sa.Float(), nullable=False),
    sa.Column('phase_greens', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('priority_phase', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], name=op.f('fk_signal_decisions_intersection_id_intersections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_decisions'))
    )
    op.create_index('ix_signal_decisions_intersection_created', 'signal_decisions', ['intersection_id', 'created_at'], unique=False)
    op.create_table('signal_plans',
    sa.Column('intersection_id', sa.Uuid(), nullable=False),
    sa.Column('phases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('min_cycle_s', sa.Float(), nullable=False),
    sa.Column('max_cycle_s', sa.Float(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], name=op.f('fk_signal_plans_intersection_id_intersections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_signal_plans_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('intersection_id', name=op.f('pk_signal_plans'))
    )
    op.create_table('signal_states',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('intersection_id', sa.Uuid(), nullable=False),
    sa.Column('reported_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('received_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('phase_name', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('GREEN', 'YELLOW', 'ALL_RED', 'FLASHING', 'OFF', name='lightstate', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('remaining_s', sa.Float(), nullable=True),
    sa.Column('mode', sa.Enum('FIXED_LOCAL', 'ADAPTIVE', 'EMERGENCY', 'FLASHING', 'OFF', name='signalmode', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['controller_clients.id'], name=op.f('fk_signal_states_client_id_controller_clients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decision_id'], ['signal_decisions.id'], name=op.f('fk_signal_states_decision_id_signal_decisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], name=op.f('fk_signal_states_intersection_id_intersections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_states'))
    )
    op.create_index('ix_signal_states_intersection_reported', 'signal_states', ['intersection_id', 'reported_at'], unique=False)
    op.create_table('traffic_metrics',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('intersection_id', sa.Uuid(), nullable=False),
    sa.Column('approach_id', sa.Uuid(), nullable=True),
    sa.Column('window_end', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('observed_vehicle_count', sa.Integer(), nullable=False),
    sa.Column('observed_stopped_count', sa.Integer(), nullable=False),
    sa.Column('observed_emergency_count', sa.Integer(), nullable=False),
    sa.Column('observed_avg_speed_mps', sa.Float(), nullable=True),
    sa.Column('observed_min_speed_mps', sa.Float(), nullable=True),
    sa.Column('observed_max_speed_mps', sa.Float(), nullable=True),
    sa.Column('calc_speed_ratio', sa.Float(), nullable=True),
    sa.Column('calc_avg_waiting_time_s', sa.Float(), nullable=True),
    sa.Column('calc_expected_arrivals_60s', sa.Integer(), nullable=True),
    sa.Column('est_vehicle_count', sa.Float(), nullable=True),
    sa.Column('est_density_veh_per_km_lane', sa.Float(), nullable=True),
    sa.Column('congestion_level', sa.String(length=16), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['approach_id'], ['intersection_approaches.id'], name=op.f('fk_traffic_metrics_approach_id_intersection_approaches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], name=op.f('fk_traffic_metrics_intersection_id_intersections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traffic_metrics'))
    )
    op.create_index('ix_traffic_metrics_intersection_time', 'traffic_metrics', ['intersection_id', 'window_end'], unique=False)
    op.create_table('tracking_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('MOBILE', 'SIMULATOR', name='telemetrysource', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('started_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.Enum('USER', 'RESTARTED', 'TIMEOUT', 'VEHICLE_SUSPENDED', 'DEMO_STOPPED', name='sessionendreason', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('max_speed_mps', sa.Float(), nullable=True),
    sa.Column('last_seq', sa.Integer(), nullable=True),
    sa.Column('last_recorded_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_lat', sa.Float(), nullable=True),
    sa.Column('last_lon', sa.Float(), nullable=True),
    sa.Column('last_accuracy_m', sa.Float(), nullable=True),
    sa.Column('jump_streak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_tracking_sessions_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_tracking_sessions_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracking_sessions'))
    )
    op.create_index('ix_tracking_sessions_vehicle_started', 'tracking_sessions', ['vehicle_id', 'started_at'], unique=False)
    op.create_table('emergency_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='emergencyeventstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('started_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_by', sa.Uuid(), nullable=True),
    sa.Column('ended_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.Enum('DRIVER', 'MANAGER', 'TIMEOUT', 'AUTH_REVOKED', 'TRACKING_STOPPED', 'VEHICLE_SUSPENDED', 'DEMO_STOPPED', name='emergencyendreason', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('ended_by', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['ended_by'], ['users.id'], name=op.f('fk_emergency_events_ended_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['tracking_sessions.id'], name=op.f('fk_emergency_events_session_id_tracking_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name=op.f('fk_emergency_events_started_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_emergency_events_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_events'))
    )
    op.create_index('ix_emergency_events_one_active_per_vehicle', 'emergency_events', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.create_index(op.f('ix_emergency_events_started_at'), 'emergency_events', ['started_at'], unique=False)
    op.create_index(op.f('ix_emergency_events_vehicle_id'), 'emergency_events', ['vehicle_id'], unique=False)
    op.create_table('vehicle_live_states',
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('MOBILE', 'SIMULATOR', name='telemetrysource', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('recorded_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('received_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=False),
    sa.Column('gps_quality', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'POOR', name='gpsquality', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('emergency', sa.Boolean(), nullable=False),
    sa.Column('usable', sa.Boolean(), nullable=False),
    sa.Column('intersection_id', sa.Uuid(), nullable=True),
    sa.Column('approach_id', sa.Uuid(), nullable=True),
    sa.Column('zone', sa.Enum('CORE', 'APPROACH', 'DEPARTURE', 'ON_LINK', name='trafficzone', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('note', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['approach_id'], ['intersection_approaches.id'], name=op.f('fk_vehicle_live_states_approach_id_intersection_approaches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], name=op.f('fk_vehicle_live_states_intersection_id_intersections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['tracking_sessions.id'], name=op.f('fk_vehicle_live_states_session_id_tracking_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_vehicle_live_states_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vehicle_id', name=op.f('pk_vehicle_live_states'))
    )
    op.create_index(op.f('ix_vehicle_live_states_recorded_at'), 'vehicle_live_states', ['recorded_at'], unique=False)
    op.create_table('vehicle_telemetry',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('MOBILE', 'SIMULATOR', name='telemetrysource', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('recorded_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('received_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('speed_source', sa.Enum('GPS', 'DERIVED', name='speedsource', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('emergency', sa.Boolean(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('usable', sa.Boolean(), nullable=False),
    sa.Column('intersection_id', sa.Uuid(), nullable=True),
    sa.Column('approach_id', sa.Uuid(), nullable=True),
    sa.Column('zone', sa.Enum('CORE', 'APPROACH', 'DEPARTURE', 'ON_LINK', name='trafficzone', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.ForeignKeyConstraint(['approach_id'], ['intersection_approaches.id'], name=op.f('fk_vehicle_telemetry_approach_id_intersection_approaches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], name=op.f('fk_vehicle_telemetry_intersection_id_intersections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['tracking_sessions.id'], name=op.f('fk_vehicle_telemetry_session_id_tracking_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_vehicle_telemetry_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_telemetry'))
    )
    op.create_index('ix_vehicle_telemetry_received', 'vehicle_telemetry', ['received_at'], unique=False)
    op.create_index(op.f('ix_vehicle_telemetry_session_id'), 'vehicle_telemetry', ['session_id'], unique=False)
    op.create_index('ix_vehicle_telemetry_vehicle_recorded', 'vehicle_telemetry', ['vehicle_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_telemetry_vehicle_recorded', table_name='vehicle_telemetry')
    op.drop_index(op.f('ix_vehicle_telemetry_session_id'), table_name='vehicle_telemetry')
    op.drop_index('ix_vehicle_telemetry_received', table_name='vehicle_telemetry')
    op.drop_table('vehicle_telemetry')
    op.drop_index(op.f('ix_vehicle_live_states_recorded_at'), table_name='vehicle_live_states')
    op.drop_table('vehicle_live_states')
    op.drop_index(op.f('ix_emergency_events_vehicle_id'), table_name='emergency_events')
    op.drop_index(op.f('ix_emergency_events_started_at'), table_name='emergency_events')
    op.drop_index('ix_emergency_events_one_active_per_vehicle', table_name='emergency_events', postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('emergency_events')
    op.drop_index('ix_tracking_sessions_vehicle_started', table_name='tracking_sessions')
    op.drop_table('tracking_sessions')
    op.drop_index('ix_traffic_metrics_intersection_time', table_name='traffic_metrics')
    op.drop_table('traffic_metrics')
    op.drop_index('ix_signal_states_intersection_reported', table_name='signal_states')
    op.drop_table('signal_states')
    op.drop_table('signal_plans')
    op.drop_index('ix_signal_decisions_intersection_created', table_name='signal_decisions')
    op.drop_table('signal_decisions')
    # ### end Alembic commands ###
